# Configuration file for code style tools

[tool.black]
line-length = 72
preview = true


[tool.isort]
line_length = 72
profile = "black"


[tool.mypy]
# From: https://justincaustin.com/blog/mypy-tips-and-tricks
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "normal"
ignore_missing_imports = true
no_implicit_reexport = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

# Ignore Alembic files
exclude = 'db/.*\.py'


[tool.pydocstyle]
# Ignore migration files
match = '^(?![0-9a-z]+_[a-z_]+).*(\.py)$'

# Only check for missing docstrings
select = [
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"
]
