"""Removed text notifs column

Revision ID: 7fa003bb32f2
Revises: aaeab4c0ba0c
Create Date: 2022-05-01 23:10:59.368575

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fa003bb32f2"
down_revision = "aaeab4c0ba0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "text_notifs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "text_notifs",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
