"""init models

Revision ID: a9d102d8d321
Revises: 
Create Date: 2022-04-03 13:11:24.193371

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9d102d8d321"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # CREATE USERS
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("netid", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_created_at"),
        "users",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_netid"), "users", ["netid"], unique=True
    )
    op.create_index(
        op.f("ix_users_updated_at"),
        "users",
        ["updated_at"],
        unique=False,
    )

    # CREATE RIDES
    op.create_table(
        "rides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=256), nullable=False),
        sa.Column("destination", sa.String(length=256), nullable=False),
        sa.Column("departure_datetime", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rides_created_at"),
        "rides",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rides_departure_datetime"),
        "rides",
        ["departure_datetime"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rides_destination"),
        "rides",
        ["destination"],
        unique=False,
    )
    op.create_index(
        op.f("ix_rides_origin"), "rides", ["origin"], unique=False
    )

    # CREATE RIDE REQUESTS
    op.create_table(
        "ride_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ride_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("status_changed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ride_id"],
            ["rides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ride_requests_created_at"),
        "ride_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ride_requests_status_changed_at"),
        "ride_requests",
        ["status_changed_at"],
        unique=False,
    )

    # CREATE RIDERS
    op.create_table(
        "riders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ride_request_id", sa.Integer(), nullable=True),
        sa.Column("ride_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_creator", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ride_id"],
            ["rides.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ride_request_id"],
            ["ride_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_riders_created_at"),
        "riders",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_riders_created_at"), table_name="riders")
    op.drop_table("riders")
    op.drop_index(
        op.f("ix_ride_requests_status_changed_at"),
        table_name="ride_requests",
    )
    op.drop_index(
        op.f("ix_ride_requests_created_at"), table_name="ride_requests"
    )
    op.drop_table("ride_requests")
    op.drop_index(op.f("ix_rides_origin"), table_name="rides")
    op.drop_index(op.f("ix_rides_destination"), table_name="rides")
    op.drop_index(
        op.f("ix_rides_departure_datetime"), table_name="rides"
    )
    op.drop_index(op.f("ix_rides_created_at"), table_name="rides")
    op.drop_table("rides")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_netid"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
