"""Changing user and ride fields to work with beta

Revision ID: aaeab4c0ba0c
Revises: eab4b2f6dade
Create Date: 2022-04-18 23:21:08.988044

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aaeab4c0ba0c"
down_revision = "eab4b2f6dade"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("text_notifs", sa.Boolean(), nullable=True)
    )
    op.drop_column("users", "anon_rides")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "anon_rides",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "text_notifs")
    # ### end Alembic commands ###
