"""Added necessary info and setttings fields to User

Revision ID: bad08d4c9ac8
Revises: a9d102d8d321
Create Date: 2022-04-03 21:22:36.612993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bad08d4c9ac8"
down_revision = "a9d102d8d321"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email", sa.String(length=256), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("disp_name", sa.String(length=256), nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("phone_num", sa.String(length=16), nullable=False),
    )
    op.add_column(
        "users", sa.Column("anon_rides", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("email_notifs", sa.Boolean(), nullable=True)
    )
    op.alter_column(
        "users",
        "netid",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "netid",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.drop_column("users", "email_notifs")
    op.drop_column("users", "anon_rides")
    op.drop_column("users", "phone_num")
    op.drop_column("users", "disp_name")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
