"""Restore text_notifs column

Revision ID: c8d4ab20e7fc
Revises: 7fa003bb32f2
Create Date: 2022-05-03 16:37:13.309062

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8d4ab20e7fc"
down_revision = "7fa003bb32f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("text_notifs", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "text_notifs")
    # ### end Alembic commands ###
