"""Made phone_num nullalbe

Revision ID: eab4b2f6dade
Revises: bad08d4c9ac8
Create Date: 2022-04-03 21:41:51.786567

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eab4b2f6dade"
down_revision = "bad08d4c9ac8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone_num",
        existing_type=sa.VARCHAR(length=16),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "phone_num",
        existing_type=sa.VARCHAR(length=16),
        nullable=False,
    )
    # ### end Alembic commands ###
